version: '3'
volumes:
  static:
  db:
services:
  web:
    build:
      context: ./
      dockerfile: ./compose/node/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - static:/code/static
    restart: always
  nginx:
    build:
      context: ./
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static:/code/static
    restart: always
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

