version: '3'
services:
  web:
    image: node
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 3000:3000
    command: npm start
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: islab
      POSTGRES_PASSWORD: Ty6Lb!Gn85hQ
      POSTGRES_DB: footage
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  nginx:
    image: nginx
    volumes:
      - ./static:/code/static
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
